/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/cabinet.glb 
*/

import React, { useEffect } from "react";
import { useGLTF, Html } from '@react-three/drei'

const Cabinet = (props) => {
  const { nodes, materials } = useGLTF('./models/cabinet.glb')
  const [showText, setShowText] = React.useState(false);
  return <>
    {showText && <Html>

    </Html>}
    <group
      {...props}
      dispose={null}
      onClick={() => setShowText(!showText)}
      onPointerEnter={() => console.log('enter')}
      onPointerLeave={() => console.log('leave')}
    >
      <group {...props} dispose={null}>
        <mesh geometry={nodes.Cube.geometry} material={materials.Cabinet} position={[-0.173, 1.782, 0.004]} scale={[1, 0.176, 1]} />
      </group>
    </group>
  </>
}

export default Cabinet

useGLTF.preload('./models/cabinet.glb')
