/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/cables.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Cables = (props) => {
  const { nodes, materials } = useGLTF('./models/cables.glb')
  return <>
    <group
      {...props}
      dispose={null}
    >
      <group {...props} dispose={null}>
        <mesh geometry={nodes.NurbsPath.geometry} material={materials['wire']} position={[-0.088, 3.923, -1.007]} rotation={[0, -0.087, -Math.PI]} scale={-1} />
        <mesh geometry={nodes.NurbsPath001.geometry} material={materials['wire']} position={[-0.233, 3.47, -0.981]} rotation={[0, -0.087, -Math.PI]} scale={-1} />
        <group position={[0.184, 3.329, -1.078]} rotation={[Math.PI / 2, 0, 0]} scale={0.06}>
          <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Metal.001']} />
          <mesh geometry={nodes.Cylinder_2.geometry} material={materials['red rubber']} />
        </group>
        <group position={[0.184, 2.233, -1.078]} rotation={[Math.PI / 2, 0, 0]} scale={0.06}>
          <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Metal.001']} />
          <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['white rubber']} />
        </group>
        <group position={[0.184, 1.098, -1.078]} rotation={[Math.PI / 2, 0, 0]} scale={0.06}>
          <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Metal.001']} />
          <mesh geometry={nodes.Cylinder002_2.geometry} material={materials['yellow rubber']} />
        </group>
        <group position={[0.184, -0.046, -1.078]} rotation={[Math.PI / 2, 0, 0]} scale={0.06}>
          <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Metal.001']} />
          <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['black rubber']} />
        </group>
        <group position={[0.184, 3.328, -0.913]} rotation={[-Math.PI / 2, 0, 0]} scale={0.085}>
          <mesh geometry={nodes.Circle001_1.geometry} material={materials['Metal.001']} />
          <mesh geometry={nodes.Circle001_2.geometry} material={materials['black plastic']} />
        </group>
        <group position={[0.184, 2.231, -0.913]} rotation={[-Math.PI / 2, 0, 0]} scale={0.085}>
          <mesh geometry={nodes.Circle002_1.geometry} material={materials['Metal.001']} />
          <mesh geometry={nodes.Circle002_2.geometry} material={materials['black plastic']} />
        </group>
        <group position={[0.184, 1.096, -0.913]} rotation={[-Math.PI / 2, 0, 0]} scale={0.085}>
          <mesh geometry={nodes.Circle003_1.geometry} material={materials['Metal.001']} />
          <mesh geometry={nodes.Circle003_2.geometry} material={materials['black plastic']} />
        </group>
        <group position={[0.184, -0.043, -0.913]} rotation={[-Math.PI / 2, 0, 0]} scale={0.085}>
          <mesh geometry={nodes.Circle004_1.geometry} material={materials['Metal.001']} />
          <mesh geometry={nodes.Circle004_2.geometry} material={materials['black plastic']} />
        </group>
        <mesh geometry={nodes.NurbsPath003.geometry} material={materials['wire']} position={[-0.325, 3.127, -1.033]} rotation={[0, -0.087, -Math.PI]} scale={-1} />
        <mesh geometry={nodes.NurbsPath004.geometry} material={materials['wire']} position={[-0.233, 3.47, -0.841]} rotation={[0, -0.087, -Math.PI]} scale={-1} />
      </group>
    </group >
  </>
}

export default Cables

useGLTF.preload('./models/cables.glb')
