/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/drawer-three.glb 
*/

import React, { useEffect } from "react";
import { useGraph } from '@react-three/fiber'
import { useGLTF, Html, useAnimations, Float } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

{/*IMPORTANT: this file is almost identical to Drawer-one.jsx and therefore is not commented.
  Go to Drawer-one.jsx to view comments*/ }

const DrawerThree = (props) => {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/drawer-three.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names, mixer } = useAnimations(animations, group)
  const [initializeLoop, setInitializeLoop] = React.useState(true);
  const [drawerIsOpen, setDrawerIsOpen] = React.useState(false);
  const [drawerTitle, setDrawerTitle] = React.useState(false);

  useEffect(() => {
    const fn = (e) => {
      switch (e.action) {
        case actions[names[1]]:
          mixer.stopAllAction();
          actions[names[5]].reset().play();
          break;
        case actions[names[2]]:
          mixer.stopAllAction();
          actions[names[4]].reset().play();
          break;
        case actions[names[0]]:
          mixer.stopAllAction();
          actions[names[3]].reset().play();
          break;
        case actions[names[6]]:
          mixer.stopAllAction();
          setDrawerIsOpen(false)
          actions[names[3]].reset().play();
          break;
      }
    }
    mixer.addEventListener('finished', fn)
    return () => {
      mixer.removeEventListener('finished', fn)
    }
  }, [mixer, names]);

  useEffect(() => {
    if (initializeLoop === true) {
      actions[names[3]].reset().play();
    } else { }
  })
  return <>
    <Float floatIntensity={3} rotationIntensity={0} speed={3}>
      {drawerTitle && <Html className="drawer_title" position={[8, 76, 2]} rotation={[-3.1415927, 1.4835301, -3.1415927]} transform occlude>
        Models
      </Html>}
    </Float>
    <group
      {...props}
      dispose={null}
      so onClick={(e) => {
        switch (drawerIsOpen) {
          case false:
            e.stopPropagation()
            actions[names[1]].repetitions = 1;
            mixer.stopAllAction();
            actions[names[1]].reset().play();
            props.onCameraPositionChange([45, 12, 0])
            props.onCameraAngleChange([0, -20, 0])
            props.setEnabled(false)
            setDrawerIsOpen(true)
            break;
          case true:
            e.stopPropagation()
            actions[names[6]].repetitions = 1;
            mixer.stopAllAction();
            setDrawerTitle(false)
            actions[names[6]].reset().play();
            props.setEnabled(true)
            break;
        }
      }}
      onPointerEnter={() => {
        if (drawerIsOpen === false) {
          actions[names[2]].repetitions = 1;
          mixer.stopAllAction();
          setDrawerTitle(true);
          actions[names[2]].reset().play();
        }
      }}
      onPointerLeave={() => {
        if (drawerIsOpen === false) {
          actions[names[0]].repetitions = 1;
          mixer.stopAllAction();
          setDrawerTitle(false);
          setInitializeLoop(false);
          actions[names[0]].reset().play();
        }
      }}
    >
      <group ref={group} {...props} dispose={null}>
        <group name="Scene">
          <group name="SliderThree" rotation={[0, 0, -Math.PI / 2]} scale={0.571}>
            <primitive object={nodes.BoneBig} />
          </group>
          <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials['Slider 1']} position={[0.497, 1.099, 0.828]} scale={[0.861, 0.054, 0.032]} />
        </group>
      </group>
    </group>
  </>;
}

export default DrawerThree

useGLTF.preload('./models/drawer-three.glb')
